baseURL = "https://clouds.re"
languageCode = "en-us"
title = "CV"
theme = "hugo-coder"

defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "sagolubev"

[params]
  author = "Sergey Golubev"
  description = "Sergey Golubev's personal cv"
  keywords = "cv,personal,devops,cloud"
  info = "System Engineer, DevOps"
  avatarurl = "images/avatar.jpg"
  favicon_16 = "images/favicon-16x16.png"
  footercontent = "Exercitatio optimus est magister. (Practice is the best teacher., lat.)"

  dateformat = "2006, January 2"

  hideCredits = true
  hideCopyright = true

  rtl = false

  colorscheme = "auto"

  # Series see also post count
  maxSeeAlsoItems = 5

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
  name = "Github"
  icon = "fab fa-github"
  weight = 1
  url = "https://github.com/sagolubev/"
[[params.social]]
  name = "Facebook"
  icon = "fab fa-facebook"
  weight = 2
  url = "https://facebook.com/sagolubev/"
[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter"
  weight = 3
  url = "https://twitter.com/sagolubev/"
[[params.social]]
  name = "LinkedIn"
  icon = "fab fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/sagolubev/"

[languages]
  [languages.en]
    languagename = "English"

    [languages.en.menu]

      [[languages.en.menu.main]]
      name = "About"
      weight = 1
      url = "about/"

      [[languages.en.menu.main]]
      name = "Technologies"
      weight = 2
      url = "tech/"

  [languages.ru]
    languagename = "Русский"
    title = "Резюме"

    [languages.ru.params]
      author = "Сергей Голубев"
      info = "Системный инженер, DevOps"
      description = "Сергей Голубев, резюме"
      keywords = "cv,personal,devops,cloud"
      footercontent = "Exercitatio optimus est magister. (Практика - лучший учитель., лат.)"

    [languages.ru.menu]

      [[languages.ru.menu.main]]
      name = "Обо мне"
      weight = 1
      url = "about/"

      [[languages.ru.menu.main]]
      name = "Технологии"
      weight = 2
      url = "tech/"
