name: publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: aks-self-hosted
    steps:
    - name: Checkout branch "master"
      uses: actions/checkout@v7
      with:
        ref: 'master'
        submodules: recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.161.0'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Copy readme
      run: |
        cp ./README.md ./public/README.md

    - name: Copy images
      run: |
        mkdir ./public/images
        cp -r ./images/* ./public/images

    - name: Copy CNAME
      run: |
        cp CNAME ./public/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: deployment

